### ISSUE TITLE
Connection to relay-analytics.ultrasound.money timed out. (connect timeout=3.05)

### ISSUE THREAD

**Issue by Amit0617** [dataalways/pbs-snapshot#1]
Tried with following command
```bash
 ./pbs_snapshot.py --max-slot 8626176 --lookback 10
```
Gives following error
```console
pbs_snapshot: INFO: downloading payload delivery data from MEV-Boost relays
pbs_snapshot: INFO: relay 'bloxroute_max_profit' returned no data; MEV share may be an underestimate
All queried relays were available!
Traceback (most recent call last):
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x79fbe71b43b0>, 'Connection to relay-analytics.ultrasound.money timed out. (connect timeout=3.05)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='relay-analytics.ultrasound.money', port=443): Max retries exceeded with url: /relay/v1/data/bidtraces/proposer_payload_delivered?cursor=8626176&limit=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79fbe71b43b0>, 'Connection to relay-analytics.ultrasound.money timed out. (connect timeout=3.05)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amit/codelib/eip4844/pbs-snapshot/./pbs_snapshot.py", line 716, in <module>
    main(
  File "/home/amit/codelib/eip4844/pbs-snapshot/./pbs_snapshot.py", line 472, in main
    data_for_relay, relay_available, rate_limited_maybe = get_data_for_relay(
                                                          ^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/pbs-snapshot/./pbs_snapshot.py", line 148, in get_data_for_relay
    bidtraces, status_code = client.proposer_payload_delivered(cursor)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/pbs-snapshot/./pbs_snapshot.py", line 113, in proposer_payload_delivered
    r = self._get(endpoint, params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/pbs-snapshot/./pbs_snapshot.py", line 76, in _get
    return requests.get(
           ^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/sessions.py", line 724, in send
    history = [resp for resp in gen]
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/sessions.py", line 265, in resolve_redirects
    resp = self.send(
           ^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amit/codelib/eip4844/venv/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='relay-analytics.ultrasound.money', port=443): Max retries exceeded with url: /relay/v1/data/bidtraces/proposer_payload_delivered?cursor=8626176&limit=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x79fbe71b43b0>, 'Connection to relay-analytics.ultrasound.money timed out. (connect timeout=3.05)'))
```

**Comment by Amit0617** [comment]
This is certainly not an internet connection issue.

**Comment by Amit0617** [comment]
Feels like that servers are quite farther or something similar. I wasn't getting in response for https://relay-analytics.ultrasound.money/relay/v1/data/bidtraces/proposer_payload_delivered in the browser too (The connection has timed out error). But now after few hours, I am getting response from it. And facing same error with https://titanrelay.xyz

**Comment by dataalways** [comment]
> Feels like that servers are quite farther or something similar. 

Ultrasound and Titan are pretty closely located (France and Germany), seems like it might be a geolocation issue. Can you increase the size of [`HTTP_CONNECT_TIMEOUT`](https://github.com/dataalways/pbs-snapshot/blob/d0de6302cb66148614b6c27169effc32f4e4a0c3/pbs_snapshot.py#L24) and see if it fixes your issues.

**Comment by Amit0617** [comment]
>  seems like it might be a geolocation issue

Yep! After an hour, both are responding quickly. All good & working!
